package polito.sdp2017.Components;
/**
 * It's the class for modeling that figures designing Ipcores, Ipmanagers, and FPGAConfigurations.
 * An Author is characterized by an unique idAuthor, a name, a company an email and a role in the company .
 */
public class Author {
	private String idAuthor;
	private String name;
	private String company;
	private String email;
	private String role;
	
	/**
	 * Constructor for class Author. Parameters are passed without performing any kind of check
	 * @param idAuthor : author identifier
	 * @param name     : author name
	 * @param company  : author company
	 * @param email    : author email
	 * @param role     : author role
	 */
	public Author(String idAuthor, String name, String company, String email, String role) {
		this.idAuthor = idAuthor;
		this.name = name;
		this.company = company;
		this.email = email;
		this.role = role;
	}
	
	/**
	 * Setter for idAuthor
	 * @param idAuthor : author identifier
	 */
	public void setIdAuthor(String idAuthor) {
		this.idAuthor = idAuthor;
	}
	
	/**
	 * Getter for idAuthor
	 * @return idAuthor
	 */
	public String getIdAuthor() {
		return this.idAuthor;
	}
	
	/**
	 * Setter for name of Author
	 * @param name : author name
	 */
	public void setName(String name) {
		this.name = name;
	}
	
	/**
	 * Getter for name of Author
	 * @return full and last name 
	 */
	public String getName() {
		return this.name;
	}
	
	/**
	 * Setter for company of Author
	 * @param company : author company
	 */
	public void setCompany(String company) {
		this.company = company;
	}
	
	/**
	 * Getter for company of Author
	 * @return the currenct company of the author
	 */
	public String getCompany() {
		return this.company;
	}
	
	/**
	 * Setter for email of Author
	 * @param email : author email
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	
	/**
	 * Getter for email of Author
	 * @return the email of the author
	 */
	public String getEmail() {
		return this.email;
	}
	
	/**
	 * Setter for role of Author
	 * @param role : author role
	 */
	public void setRole(String role) {
		this.role = role;
	}
	
	/**
	 * Getter role of Author
	 * @return the tole of the author
	 */
	public String getRole() {
		return this.role;
	}
	
	/**
	 * auto-generated by Eclipse
	 * @return hash code of the object
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((company == null) ? 0 : company.hashCode());
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result + ((idAuthor == null) ? 0 : idAuthor.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((role == null) ? 0 : role.hashCode());
		return result;
	}
	
	/**
	 * auto-generated by Eclipse
	 * @return boolean indicating if the two objects are equal.
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Author other = (Author) obj;
		if (company == null) {
			if (other.company != null)
				return false;
		} else if (!company.equals(other.company))
			return false;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (idAuthor == null) {
			if (other.idAuthor != null)
				return false;
		} else if (!idAuthor.equals(other.idAuthor))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (role == null) {
			if (other.role != null)
				return false;
		} else if (!role.equals(other.role))
			return false;
		return true;
	}
	
	/**
	 * @return String representation of all information on the author
	 */
	@Override
	public String toString() {
		return "Author: \t" + idAuthor + "\nName: \t\t" + name + "\nCompany: \t" + company + 
				"\nEmail: \t\t" + email + "\nRole: \t\t" + role ;
	}
}
