package polito.sdp2017.DesignEnvironmentGui;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * Main class is the entry point for the application, where the GUI starts. It is in charge of
 * loading all the screens the application uses and displaying the first screen.
 */
public class Main extends Application {
    public static final String screenStartID = "start";					//	identifier for the start screen
    public static final String screenManageIPID = "manageIP";			//	identifier for the manageIP screen
    public static final String screenCreateConfigID = "createConfig";	//	identifier for the createConfig screen
    public static final String screenManageConfigID = "manageConfig";	//	identifier for the manageConfig screen

    public static final String screenStartFile = "ScreenStart.fxml";
    public static final String screenManageIPFile = "ScreenManageIP.fxml";
    public static final String screenCreateConfigFile = "ScreenCreateConfig.fxml";
    public static final String screenManageConfigFile = "ScreenManageConfig.fxml";
    
	/**
	 * auto-generated by Eclipse, this is called by javaFX.
	 */
    @Override
    public void start(Stage primaryStage) {
        ScreensController mainContainer = new ScreensController();	//	main container for all the screens
    	ApplicationModel appModel = new ApplicationModel();			//	the application implements the
    																//	MODEL-VIEW-CONTROLLER
        
        mainContainer.loadScreen(Main.screenStartID, Main.screenStartFile, appModel);
        mainContainer.loadScreen(Main.screenManageIPID, Main.screenManageIPFile, appModel);
        mainContainer.loadScreen(Main.screenCreateConfigID, Main.screenCreateConfigFile, appModel);
        mainContainer.loadScreen(Main.screenManageConfigID, Main.screenManageConfigFile, appModel);
        
        mainContainer.setScreen(Main.screenStartID);	//	sets the first screen to be displayed
        
        Group root = new Group();
        root.getChildren().addAll(mainContainer);
        Scene scene = new Scene(root);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Design environment for LATTICE based FPGA boards");
        primaryStage.show();
    }

	/**
	 * auto-generated by Eclipse, this is the expected entry point for any javaFX application.
	 */
    public static void main(String[] args) {
        launch(args);
    }
}
